name: Bug report
description: Report a bug or unexpected behavior

labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please provide as much detail as possible to help us reproduce and fix the problem. Don't forget to give us a star!
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue step by step
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. With config '...'
        3. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Error output / Logs
      description: If applicable, paste the error message or relevant logs.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Configuration
      description: Share your (sanitized) configuration file if relevant.
      render: yaml
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Environment information where the problem occurs.
      value: |
        - kafka-partition-remapper version:
        - OS:
        - Kafka version:
        - Security protocol: [PLAINTEXT / SSL / SASL_PLAINTEXT / SASL_SSL]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
